export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced';

export interface AIUpgrade {
  title: string;
  description: string;
  concept: string;
}

/** The validated, render-safe result of AI-ifying a project. Never raw model text. */
export interface Blueprint {
  id: string;
  original: string;
  projectName: string;
  summary: string;
  aiUpgrades: AIUpgrade[];
  techStack: string[];
  difficulty: Difficulty;
  estimatedTime: string;
  score: number;
  whyItWorks: string;
  aiConcepts: string[];
  /** 'ai' = generated by the LLM, 'pattern' = matched from the built-in library. */
  source: 'ai' | 'pattern';
  patternId?: string;
  createdAt: string;
}

export const SOURCES = ['whatsapp', 'poster', 'instagram', 'club', 'ambassador', 'linkedin', 'qr', 'referral', 'direct', 'other'] as const;
export type Source = (typeof SOURCES)[number];

export interface Attribution {
  source: Source;
  campaign?: string;
  ref?: string;
  landing?: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  emailKey: string;
  phone: string;
  college: string;
  collegeKey: string;
  branch: string;
  year: string;
  originalProject?: string;
  generatedProject?: string;
  blueprintId?: string;
  referralCode: string;
  referredBy?: string;
  referralCount: number;
  rewardUnlocked: boolean;
  source: Source;
  campaign?: string;
  ipHash?: string;
  dashToken: string;
  demo?: boolean;
  createdAt: string;
}

export type ReferralStatus = 'completed' | 'held';

export interface Referral {
  id: string;
  referrerId: string;
  referredUserId: string;
  referralCode: string;
  status: ReferralStatus;
  reason?: string;
  createdAt: string;
}

export interface CollegeSeed {
  key: string;
  name: string;
  city: string;
  builders: number;
}

export interface AnalyticsEvent {
  name: EventName;
  ts: string;
  sessionId: string;
  source?: Source;
  campaign?: string;
  college?: string;
  props?: Record<string, string | number | boolean | null>;
}

export const EVENT_NAMES = [
  'page_view',
  'project_input_started',
  'project_generated',
  'project_shared',
  'registration_started',
  'registration_completed',
  'whatsapp_clicked',
  'referral_link_copied',
  'referral_link_opened',
  'referral_registered',
  'reward_unlocked',
  'leaderboard_viewed',
  'workshop_cta_clicked',
] as const;
export type EventName = (typeof EVENT_NAMES)[number];

/** What the dashboard sees — no contact details, friends by first name only. */
export interface PublicUser {
  firstName: string;
  college: string;
  collegeKey: string;
  referralCode: string;
  referralCount: number;
  rewardUnlocked: boolean;
  generatedProject?: string;
  blueprintId?: string;
  friends: { firstName: string; joinedAt: string }[];
  createdAt: string;
}

export interface LeaderboardEntry {
  rank: number;
  key: string;
  name: string;
  city?: string;
  builders: number;
  monogram: string;
}

export interface LeaderboardResult {
  entries: LeaderboardEntry[];
  you?: LeaderboardEntry & { toNext?: number; nextName?: string };
  total: number;
}

export type RegisterErrorCode =
  | 'duplicate_email'
  | 'duplicate_phone'
  | 'disposable_email'
  | 'invalid';

export interface RegisterResult {
  status: 'created' | 'existing';
  user: PublicUser;
  dashToken: string;
  notices: ('invalid_referral' | 'self_referral' | 'referral_held')[];
}
